-- ============================================================================
-- 台灣高鐵訂票系統：Supabase / PostgreSQL 15+ 最終正式版
--
-- 使用方式：在全新的 Supabase 專案 SQL Editor 中完整執行本檔一次。
-- 本檔已整合原始結構與 001-008 全部 migration；請勿再重複執行舊檔。
-- 執行成功後，再執行同資料夾的 02_seed.sql。
-- ============================================================================

BEGIN;

SET search_path TO public;

-- ----------------------------------------------------------------------------
-- 列舉型別
-- PostgreSQL 沒有 MySQL 的欄位內 ENUM 語法，因此先建立命名型別。
-- duplicate_object 例外處理讓已存在的相同型別可以被沿用。
-- ----------------------------------------------------------------------------

DO $$
BEGIN
    CREATE TYPE thsr_passenger_type AS ENUM (
        'ADULT', 'CHILD', 'SENIOR', 'DISABLED'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
    CREATE TYPE thsr_seat_type AS ENUM (
        'STANDARD', 'BUSINESS', 'ACCESSIBLE'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
    CREATE TYPE thsr_seat_position AS ENUM (
        'WINDOW', 'AISLE', 'MIDDLE'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
    CREATE TYPE thsr_schedule_status AS ENUM (
        'SCHEDULED', 'BOARDING', 'DEPARTED', 'ARRIVED', 'CANCELLED'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
    CREATE TYPE thsr_booking_status AS ENUM (
        'PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
    CREATE TYPE thsr_fare_type AS ENUM (
        'FULL', 'CHILD', 'SENIOR', 'DISABLED', 'STUDENT', 'EARLY_BIRD'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
    CREATE TYPE thsr_payment_method AS ENUM (
        'CREDIT_CARD', 'ATM', 'CONVENIENCE_STORE', 'MOBILE_PAYMENT'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
    CREATE TYPE thsr_payment_status AS ENUM (
        'PENDING', 'PAID', 'FAILED', 'REFUNDED'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
    CREATE TYPE thsr_ticket_status AS ENUM (
        'ISSUED', 'USED', 'CANCELLED'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END;
$$;

-- ----------------------------------------------------------------------------
-- 會員與乘客
-- ----------------------------------------------------------------------------

CREATE TABLE members (
    member_id      bigint GENERATED BY DEFAULT AS IDENTITY,
    name           varchar(100) NOT NULL,
    email          varchar(254) NOT NULL,
    phone          varchar(20),
    password_hash  varchar(255) NOT NULL,
    created_at     timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_members PRIMARY KEY (member_id),
    CONSTRAINT uq_members_email UNIQUE (email),
    CONSTRAINT uq_members_phone UNIQUE (phone)
);

COMMENT ON TABLE members IS '會員';
COMMENT ON COLUMN members.member_id IS '會員流水號';
COMMENT ON COLUMN members.password_hash IS '密碼雜湊；不可存明文密碼';

CREATE TABLE passengers (
    passenger_id    bigint GENERATED BY DEFAULT AS IDENTITY,
    member_id       bigint NOT NULL,
    name            varchar(100) NOT NULL,
    id_number       varchar(32) NOT NULL,
    passenger_type  thsr_passenger_type NOT NULL DEFAULT 'ADULT',
    created_at      timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_passengers PRIMARY KEY (passenger_id),
    CONSTRAINT uq_passengers_member_document UNIQUE (member_id, id_number),
    CONSTRAINT fk_passengers_member
        FOREIGN KEY (member_id) REFERENCES members (member_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

COMMENT ON TABLE passengers IS '會員保存的乘客資料';
COMMENT ON COLUMN passengers.id_number IS '證件號碼；正式系統應加密或代碼化';

-- ----------------------------------------------------------------------------
-- 列車、座位、車站與每日班次
-- ----------------------------------------------------------------------------

CREATE TABLE trains (
    train_id      bigint GENERATED BY DEFAULT AS IDENTITY,
    train_number  varchar(10) NOT NULL,
    train_type    varchar(50) NOT NULL,
    CONSTRAINT pk_trains PRIMARY KEY (train_id),
    CONSTRAINT uq_trains_number UNIQUE (train_number)
);

COMMENT ON TABLE trains IS '列車／車次主檔';

CREATE TABLE seats (
    seat_id          bigint GENERATED BY DEFAULT AS IDENTITY,
    train_id         bigint NOT NULL,
    carriage_number  smallint NOT NULL,
    seat_number      varchar(5) NOT NULL,
    seat_type        thsr_seat_type NOT NULL DEFAULT 'STANDARD',
    seat_position    thsr_seat_position NOT NULL,
    CONSTRAINT pk_seats PRIMARY KEY (seat_id),
    CONSTRAINT uq_seats_train_position
        UNIQUE (train_id, carriage_number, seat_number),
    CONSTRAINT ck_seats_carriage_positive CHECK (carriage_number > 0),
    CONSTRAINT fk_seats_train
        FOREIGN KEY (train_id) REFERENCES trains (train_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

COMMENT ON TABLE seats IS '列車座位';
COMMENT ON COLUMN seats.seat_position IS '座位位置：靠窗、走道或中間座位';

CREATE INDEX idx_seats_train_type_position
    ON seats (train_id, seat_type, seat_position);

CREATE TABLE stations (
    station_id       bigint GENERATED BY DEFAULT AS IDENTITY,
    station_code     varchar(10) NOT NULL,
    station_name     varchar(100) NOT NULL,
    station_name_en  varchar(100) NOT NULL,
    city             varchar(100) NOT NULL,
    station_order    smallint NOT NULL,
    CONSTRAINT pk_stations PRIMARY KEY (station_id),
    CONSTRAINT uq_stations_code UNIQUE (station_code),
    CONSTRAINT uq_stations_order UNIQUE (station_order),
    CONSTRAINT ck_stations_order_positive CHECK (station_order > 0)
);

COMMENT ON TABLE stations IS '車站';

CREATE TABLE fares (
    fare_id                 bigint GENERATED BY DEFAULT AS IDENTITY,
    origin_station_id       bigint NOT NULL,
    destination_station_id  bigint NOT NULL,
    seat_type               thsr_seat_type NOT NULL,
    fare_type               thsr_fare_type NOT NULL,
    amount                  numeric(10, 2) NOT NULL,
    CONSTRAINT pk_fares PRIMARY KEY (fare_id),
    CONSTRAINT uq_fares_route_seat_type
        UNIQUE (
            origin_station_id,
            destination_station_id,
            seat_type,
            fare_type
        ),
    CONSTRAINT ck_fares_distinct_stations CHECK (
        origin_station_id <> destination_station_id
    ),
    CONSTRAINT ck_fares_amount_positive CHECK (amount > 0),
    CONSTRAINT fk_fares_origin_station
        FOREIGN KEY (origin_station_id) REFERENCES stations (station_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_fares_destination_station
        FOREIGN KEY (destination_station_id) REFERENCES stations (station_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

COMMENT ON TABLE fares IS '現行票價主檔；依起迄站、座位類型與票種定價';
COMMENT ON COLUMN fares.amount IS '用於報價；訂票後的成交價另存於 booking_items.fare_amount';

CREATE TABLE train_schedules (
    schedule_id  bigint GENERATED BY DEFAULT AS IDENTITY,
    train_id     bigint NOT NULL,
    service_date date NOT NULL,
    status       thsr_schedule_status NOT NULL DEFAULT 'SCHEDULED',
    CONSTRAINT pk_train_schedules PRIMARY KEY (schedule_id),
    CONSTRAINT uq_train_schedules_train_date UNIQUE (train_id, service_date),
    CONSTRAINT fk_train_schedules_train
        FOREIGN KEY (train_id) REFERENCES trains (train_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

COMMENT ON TABLE train_schedules IS '每日實際行駛班次';

CREATE TABLE train_stops (
    stop_id        bigint GENERATED BY DEFAULT AS IDENTITY,
    schedule_id    bigint NOT NULL,
    station_id     bigint NOT NULL,
    stop_order     smallint NOT NULL,
    arrival_at     timestamptz,
    departure_at   timestamptz,
    CONSTRAINT pk_train_stops PRIMARY KEY (stop_id),
    CONSTRAINT uq_train_stops_schedule_order UNIQUE (schedule_id, stop_order),
    CONSTRAINT uq_train_stops_schedule_station UNIQUE (schedule_id, station_id),
    CONSTRAINT ck_train_stops_order_positive CHECK (stop_order > 0),
    CONSTRAINT ck_train_stops_time_order CHECK (
        arrival_at IS NULL
        OR departure_at IS NULL
        OR arrival_at <= departure_at
    ),
    CONSTRAINT fk_train_stops_schedule
        FOREIGN KEY (schedule_id) REFERENCES train_schedules (schedule_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_train_stops_station
        FOREIGN KEY (station_id) REFERENCES stations (station_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

COMMENT ON TABLE train_stops IS '某一每日班次的停靠站與時刻';

CREATE TABLE schedule_segments (
    segment_id    bigint GENERATED BY DEFAULT AS IDENTITY,
    from_stop_id  bigint NOT NULL,
    to_stop_id    bigint NOT NULL,
    CONSTRAINT pk_schedule_segments PRIMARY KEY (segment_id),
    -- 每一停靠點最多只會接出／接入一個相鄰區間，因此兩者都是候選鍵。
    CONSTRAINT uq_schedule_segments_from_stop UNIQUE (from_stop_id),
    CONSTRAINT uq_schedule_segments_to_stop UNIQUE (to_stop_id),
    CONSTRAINT ck_schedule_segments_distinct_stops
        CHECK (from_stop_id <> to_stop_id),
    CONSTRAINT fk_schedule_segments_from_stop
        FOREIGN KEY (from_stop_id) REFERENCES train_stops (stop_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_schedule_segments_to_stop
        FOREIGN KEY (to_stop_id) REFERENCES train_stops (stop_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

COMMENT ON TABLE schedule_segments IS '同一班次中兩個相鄰停靠點之間的區間';

-- ----------------------------------------------------------------------------
-- 訂單、訂票項目與座位區間鎖定
-- ----------------------------------------------------------------------------

CREATE TABLE bookings (
    booking_id      bigint GENERATED BY DEFAULT AS IDENTITY,
    member_id       bigint NOT NULL,
    booking_number  varchar(30) NOT NULL,
    booking_status  thsr_booking_status NOT NULL DEFAULT 'PENDING',
    created_at      timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_bookings PRIMARY KEY (booking_id),
    CONSTRAINT uq_bookings_number UNIQUE (booking_number),
    CONSTRAINT fk_bookings_member
        FOREIGN KEY (member_id) REFERENCES members (member_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

COMMENT ON TABLE bookings IS '訂單主檔；總額由訂票項目加總取得';

CREATE TABLE booking_items (
    booking_item_id      bigint GENERATED BY DEFAULT AS IDENTITY,
    booking_id           bigint NOT NULL,
    passenger_id         bigint NOT NULL,
    seat_id              bigint NOT NULL,
    origin_stop_id       bigint NOT NULL,
    destination_stop_id  bigint NOT NULL,
    fare_type            thsr_fare_type NOT NULL DEFAULT 'FULL',
    fare_amount          numeric(10, 2) NOT NULL,
    created_at           timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_booking_items PRIMARY KEY (booking_item_id),
    -- 供座位區間表以複合外鍵驗證 booking_item_id 與 seat_id 的一致性。
    CONSTRAINT uq_booking_items_id_seat UNIQUE (booking_item_id, seat_id),
    CONSTRAINT ck_booking_items_distinct_stops CHECK (
        origin_stop_id <> destination_stop_id
    ),
    CONSTRAINT ck_booking_items_fare_nonnegative CHECK (fare_amount >= 0),
    CONSTRAINT fk_booking_items_booking
        FOREIGN KEY (booking_id) REFERENCES bookings (booking_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_booking_items_passenger
        FOREIGN KEY (passenger_id) REFERENCES passengers (passenger_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_booking_items_seat
        FOREIGN KEY (seat_id) REFERENCES seats (seat_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_booking_items_origin_stop
        FOREIGN KEY (origin_stop_id) REFERENCES train_stops (stop_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_booking_items_destination_stop
        FOREIGN KEY (destination_stop_id) REFERENCES train_stops (stop_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

COMMENT ON TABLE booking_items IS '一張訂單中的一位乘客、一段旅程及其成交票價';

CREATE TABLE seat_segment_reservations (
    segment_id      bigint NOT NULL,
    seat_id         bigint NOT NULL,
    booking_item_id bigint NOT NULL,
    reserved_at     timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 同一區間的同一座位只能出現一次，直接阻止重複售票。
    CONSTRAINT pk_seat_segment_reservations PRIMARY KEY (segment_id, seat_id),
    CONSTRAINT uq_seat_segment_booking_item UNIQUE (booking_item_id, segment_id),
    CONSTRAINT fk_seat_segment_segment
        FOREIGN KEY (segment_id) REFERENCES schedule_segments (segment_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_seat_segment_booking_item_seat
        FOREIGN KEY (booking_item_id, seat_id)
        REFERENCES booking_items (booking_item_id, seat_id)
        ON UPDATE RESTRICT ON DELETE CASCADE
);

COMMENT ON TABLE seat_segment_reservations IS '座位在各相鄰站間區間的占用紀錄';

-- ----------------------------------------------------------------------------
-- 付款與票券
-- ----------------------------------------------------------------------------

CREATE TABLE payments (
    payment_id      bigint GENERATED BY DEFAULT AS IDENTITY,
    booking_id      bigint NOT NULL,
    amount          numeric(10, 2) NOT NULL,
    payment_method  thsr_payment_method NOT NULL,
    payment_status  thsr_payment_status NOT NULL DEFAULT 'PENDING',
    transaction_id  varchar(100),
    paid_at         timestamptz,
    created_at      timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_payments PRIMARY KEY (payment_id),
    CONSTRAINT uq_payments_transaction UNIQUE (transaction_id),
    CONSTRAINT ck_payments_amount_positive CHECK (amount > 0),
    CONSTRAINT ck_payments_paid_time CHECK (
        payment_status NOT IN ('PAID', 'REFUNDED') OR paid_at IS NOT NULL
    ),
    CONSTRAINT fk_payments_booking
        FOREIGN KEY (booking_id) REFERENCES bookings (booking_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

COMMENT ON TABLE payments IS '付款嘗試與結果；一張訂單可有多次付款紀錄';

CREATE TABLE tickets (
    ticket_id       bigint GENERATED BY DEFAULT AS IDENTITY,
    booking_item_id bigint NOT NULL,
    ticket_number   varchar(40) NOT NULL,
    status          thsr_ticket_status NOT NULL DEFAULT 'ISSUED',
    issued_at       timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_tickets PRIMARY KEY (ticket_id),
    CONSTRAINT uq_tickets_booking_item UNIQUE (booking_item_id),
    CONSTRAINT uq_tickets_number UNIQUE (ticket_number),
    CONSTRAINT fk_tickets_booking_item
        FOREIGN KEY (booking_item_id) REFERENCES booking_items (booking_item_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

COMMENT ON TABLE tickets IS '已開立票券；票種與成交價由訂票項目取得';

-- ----------------------------------------------------------------------------
-- Supabase Row Level Security
-- 搜尋班次需要公開讀取主檔與時刻表；會員與交易表不開放匿名存取。
-- ----------------------------------------------------------------------------

ALTER TABLE stations ENABLE ROW LEVEL SECURITY;
ALTER TABLE fares ENABLE ROW LEVEL SECURITY;
ALTER TABLE trains ENABLE ROW LEVEL SECURITY;
ALTER TABLE seats ENABLE ROW LEVEL SECURITY;
ALTER TABLE train_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE train_stops ENABLE ROW LEVEL SECURITY;
ALTER TABLE schedule_segments ENABLE ROW LEVEL SECURITY;

CREATE POLICY public_read ON stations
FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY public_read ON fares
FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY public_read ON trains
FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY public_read ON seats
FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY public_read ON train_schedules
FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY public_read ON train_stops
FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY public_read ON schedule_segments
FOR SELECT TO anon, authenticated USING (true);

-- ----------------------------------------------------------------------------
-- 跨資料表商業規則
-- PostgreSQL 使用 PL/pgSQL trigger function，再將 function 綁定到 trigger。
-- ----------------------------------------------------------------------------

-- 驗證行車區間的起訖停靠點屬於同一班次，而且兩站必須相鄰。
CREATE OR REPLACE FUNCTION fn_validate_schedule_segment_insert()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
    v_from_schedule bigint;
    v_to_schedule   bigint;
    v_from_order    smallint;
    v_to_order      smallint;
BEGIN
    SELECT schedule_id, stop_order
      INTO v_from_schedule, v_from_order
      FROM train_stops
     WHERE stop_id = NEW.from_stop_id;

    SELECT schedule_id, stop_order
      INTO v_to_schedule, v_to_order
      FROM train_stops
     WHERE stop_id = NEW.to_stop_id;

    IF v_from_schedule IS DISTINCT FROM v_to_schedule THEN
        RAISE EXCEPTION '區間的起點與終點必須屬於同一班次';
    END IF;

    IF v_to_order IS DISTINCT FROM v_from_order + 1 THEN
        RAISE EXCEPTION '區間的終點必須是起點的下一個停靠站';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER bi_schedule_segments_validate
BEFORE INSERT ON schedule_segments
FOR EACH ROW
EXECUTE FUNCTION fn_validate_schedule_segment_insert();

-- 區間建立後不可改接其他停靠點，以免既有預訂指向錯誤區間。
CREATE OR REPLACE FUNCTION fn_prevent_schedule_segment_endpoint_update()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
    IF NEW.from_stop_id IS DISTINCT FROM OLD.from_stop_id
       OR NEW.to_stop_id IS DISTINCT FROM OLD.to_stop_id THEN
        RAISE EXCEPTION '不可修改既有區間端點；請刪除後重新建立';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER bu_schedule_segments_validate
BEFORE UPDATE ON schedule_segments
FOR EACH ROW
EXECUTE FUNCTION fn_prevent_schedule_segment_endpoint_update();

-- 驗證訂票項目的班次、起訖順序、座位列車、會員與完整區間。
CREATE OR REPLACE FUNCTION fn_validate_booking_item_insert()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
    v_origin_schedule     bigint;
    v_destination_sched  bigint;
    v_origin_order        smallint;
    v_destination_order   smallint;
    v_schedule_train      bigint;
    v_seat_train          bigint;
    v_booking_member      bigint;
    v_passenger_member    bigint;
    v_segment_count       bigint;
BEGIN
    SELECT schedule_id, stop_order
      INTO v_origin_schedule, v_origin_order
      FROM train_stops
     WHERE stop_id = NEW.origin_stop_id;

    SELECT schedule_id, stop_order
      INTO v_destination_sched, v_destination_order
      FROM train_stops
     WHERE stop_id = NEW.destination_stop_id;

    IF v_origin_schedule IS DISTINCT FROM v_destination_sched THEN
        RAISE EXCEPTION '起站與迄站必須屬於同一班次';
    END IF;

    IF v_origin_order >= v_destination_order THEN
        RAISE EXCEPTION '起站順序必須早於迄站';
    END IF;

    SELECT train_id
      INTO v_schedule_train
      FROM train_schedules
     WHERE schedule_id = v_origin_schedule;

    SELECT train_id
      INTO v_seat_train
      FROM seats
     WHERE seat_id = NEW.seat_id;

    IF v_schedule_train IS DISTINCT FROM v_seat_train THEN
        RAISE EXCEPTION '所選座位不屬於此班次的列車';
    END IF;

    SELECT member_id
      INTO v_booking_member
      FROM bookings
     WHERE booking_id = NEW.booking_id;

    SELECT member_id
      INTO v_passenger_member
      FROM passengers
     WHERE passenger_id = NEW.passenger_id;

    IF v_booking_member IS DISTINCT FROM v_passenger_member THEN
        RAISE EXCEPTION '乘客資料不屬於下單會員';
    END IF;

    -- 旅程跨越 n 個停靠序差，就必須存在 n 個相鄰區間。
    SELECT COUNT(*)
      INTO v_segment_count
      FROM schedule_segments AS sg
      JOIN train_stops AS fs ON fs.stop_id = sg.from_stop_id
     WHERE fs.schedule_id = v_origin_schedule
       AND fs.stop_order >= v_origin_order
       AND fs.stop_order < v_destination_order;

    IF v_segment_count <> v_destination_order - v_origin_order THEN
        RAISE EXCEPTION '此班次的相鄰行車區間尚未完整建立';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER bi_booking_items_validate
BEFORE INSERT ON booking_items
FOR EACH ROW
EXECUTE FUNCTION fn_validate_booking_item_insert();

-- 已鎖位後不可直接更換訂單、乘客、座位或行程。
CREATE OR REPLACE FUNCTION fn_prevent_booking_item_trip_update()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
    IF NEW.booking_id IS DISTINCT FROM OLD.booking_id
       OR NEW.passenger_id IS DISTINCT FROM OLD.passenger_id
       OR NEW.seat_id IS DISTINCT FROM OLD.seat_id
       OR NEW.origin_stop_id IS DISTINCT FROM OLD.origin_stop_id
       OR NEW.destination_stop_id IS DISTINCT FROM OLD.destination_stop_id THEN
        RAISE EXCEPTION '不可直接修改已鎖位項目的訂單、乘客、座位或行程';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER bu_booking_items_immutable_trip
BEFORE UPDATE ON booking_items
FOR EACH ROW
EXECUTE FUNCTION fn_prevent_booking_item_trip_update();

-- 新增訂票項目後，自動鎖住旅程涵蓋的每個相鄰區間。
-- 若任一區間已被同一座位占用，複合主鍵會讓整筆交易原子性失敗。
CREATE OR REPLACE FUNCTION fn_reserve_booking_item_segments()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
    INSERT INTO seat_segment_reservations (
        segment_id,
        seat_id,
        booking_item_id
    )
    SELECT
        sg.segment_id,
        NEW.seat_id,
        NEW.booking_item_id
      FROM schedule_segments AS sg
      JOIN train_stops AS fs ON fs.stop_id = sg.from_stop_id
      JOIN train_stops AS os ON os.stop_id = NEW.origin_stop_id
      JOIN train_stops AS ds ON ds.stop_id = NEW.destination_stop_id
     WHERE fs.schedule_id = os.schedule_id
       AND fs.stop_order >= os.stop_order
       AND fs.stop_order < ds.stop_order;

    RETURN NEW;
END;
$$;

CREATE TRIGGER ai_booking_items_reserve_segments
AFTER INSERT ON booking_items
FOR EACH ROW
EXECUTE FUNCTION fn_reserve_booking_item_segments();

-- ----------------------------------------------------------------------------
-- 衍生查詢：訂單總額不重複存入 bookings，而由明細即時計算。
-- ----------------------------------------------------------------------------

CREATE OR REPLACE VIEW v_booking_totals AS
SELECT
    b.booking_id,
    b.booking_number,
    COALESCE(SUM(bi.fare_amount), 0.00::numeric) AS total_amount
FROM bookings AS b
LEFT JOIN booking_items AS bi
       ON bi.booking_id = b.booking_id
GROUP BY b.booking_id, b.booking_number;

COMMENT ON VIEW v_booking_totals IS '依訂票項目即時計算的訂單總額';


-- ============================================================================
-- CAPTCHA、Supabase Auth 與原子訂位 API
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- CAPTCHA solutions are HMAC digests created by the Next.js server. The raw
-- solution is never persisted and each challenge is bound to a client fingerprint.
CREATE TABLE IF NOT EXISTS captcha_challenges (
    challenge_id       uuid PRIMARY KEY,
    answer_digest      char(64) NOT NULL,
    client_fingerprint char(64) NOT NULL,
    attempts           smallint NOT NULL DEFAULT 0,
    expires_at         timestamptz NOT NULL,
    used_at            timestamptz,
    created_at         timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_captcha_attempts CHECK (attempts BETWEEN 0 AND 5),
    CONSTRAINT ck_captcha_expiry CHECK (expires_at > created_at)
);

CREATE INDEX IF NOT EXISTS idx_captcha_fingerprint_created
    ON captcha_challenges (client_fingerprint, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_captcha_expiry
    ON captcha_challenges (expires_at);

ALTER TABLE captcha_challenges ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION issue_captcha_challenge(
    p_challenge_id uuid,
    p_answer_digest text,
    p_client_fingerprint text,
    p_expires_at timestamptz
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    IF length(p_answer_digest) <> 64 OR length(p_client_fingerprint) <> 64
       OR p_expires_at <= now() OR p_expires_at > now() + interval '10 minutes' THEN
        RAISE EXCEPTION 'CAPTCHA_INVALID_INPUT';
    END IF;

    -- Serialize issuance per fingerprint so concurrent requests cannot bypass the limit.
    PERFORM pg_advisory_xact_lock(hashtextextended('captcha:' || p_client_fingerprint, 0));

    DELETE FROM captcha_challenges
     WHERE expires_at < now() - interval '1 day';

    IF (
        SELECT count(*)
          FROM captcha_challenges
         WHERE client_fingerprint = p_client_fingerprint
           AND created_at >= now() - interval '10 minutes'
    ) >= 30 THEN
        RAISE EXCEPTION 'CAPTCHA_RATE_LIMITED';
    END IF;

    INSERT INTO captcha_challenges (
        challenge_id,
        answer_digest,
        client_fingerprint,
        expires_at
    ) VALUES (
        p_challenge_id,
        p_answer_digest,
        p_client_fingerprint,
        p_expires_at
    );

    RETURN true;
END;
$$;

CREATE OR REPLACE FUNCTION consume_captcha_challenge(
    p_challenge_id uuid,
    p_answer_digest text,
    p_client_fingerprint text
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_challenge captcha_challenges%ROWTYPE;
BEGIN
    SELECT *
      INTO v_challenge
      FROM captcha_challenges
     WHERE challenge_id = p_challenge_id
     FOR UPDATE;

    IF NOT FOUND OR v_challenge.client_fingerprint <> p_client_fingerprint THEN
        RETURN 'INVALID';
    END IF;
    IF v_challenge.used_at IS NOT NULL THEN
        RETURN 'INVALID';
    END IF;
    IF v_challenge.expires_at <= now() THEN
        RETURN 'EXPIRED';
    END IF;
    IF v_challenge.attempts >= 5 THEN
        RETURN 'LOCKED';
    END IF;

    IF v_challenge.answer_digest <> p_answer_digest THEN
        UPDATE captcha_challenges
           SET attempts = attempts + 1
         WHERE challenge_id = p_challenge_id;
        IF v_challenge.attempts + 1 >= 5 THEN
            RETURN 'LOCKED';
        END IF;
        RETURN 'INVALID';
    END IF;

    UPDATE captcha_challenges
       SET used_at = now()
     WHERE challenge_id = p_challenge_id;
    RETURN 'VALID';
END;
$$;

REVOKE ALL ON TABLE captcha_challenges FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION issue_captcha_challenge(uuid, text, text, timestamptz) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION consume_captcha_challenge(uuid, text, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION issue_captcha_challenge(uuid, text, text, timestamptz) TO service_role;
GRANT EXECUTE ON FUNCTION consume_captcha_challenge(uuid, text, text) TO service_role;

-- Link application members to Supabase Auth. Transaction tables remain private;
-- authenticated users can access them only through the ownership-checking RPCs below.
ALTER TABLE members ADD COLUMN IF NOT EXISTS auth_user_id uuid;
CREATE UNIQUE INDEX IF NOT EXISTS uq_members_auth_user_id
    ON members (auth_user_id) WHERE auth_user_id IS NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conname = 'fk_members_auth_user'
           AND conrelid = 'public.members'::regclass
    ) THEN
        ALTER TABLE members
            ADD CONSTRAINT fk_members_auth_user
            FOREIGN KEY (auth_user_id) REFERENCES auth.users (id)
            ON UPDATE RESTRICT ON DELETE RESTRICT;
    END IF;
END;
$$;

ALTER TABLE bookings ADD COLUMN IF NOT EXISTS idempotency_key uuid;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS expires_at timestamptz;
ALTER TABLE passengers ADD COLUMN IF NOT EXISTS student_verified_until date;
ALTER TABLE bookings ALTER COLUMN expires_at SET DEFAULT (now() + interval '10 minutes');
UPDATE bookings
   SET expires_at = created_at + interval '10 minutes'
 WHERE expires_at IS NULL;
ALTER TABLE bookings ALTER COLUMN expires_at SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_bookings_member_idempotency
    ON bookings (member_id, idempotency_key)
    WHERE idempotency_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_bookings_pending_expiry
    ON bookings (expires_at)
    WHERE booking_status = 'PENDING';
CREATE INDEX IF NOT EXISTS idx_booking_items_booking_id
    ON booking_items (booking_id);

ALTER TABLE members ENABLE ROW LEVEL SECURITY;
ALTER TABLE passengers ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE booking_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE seat_segment_reservations ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE tickets ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION build_booking_response(p_booking_id bigint, p_replayed boolean DEFAULT false)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
    SELECT jsonb_build_object(
        'bookingId', b.booking_id,
        'bookingNumber', b.booking_number,
        'status', b.booking_status,
        'createdAt', b.created_at,
        'expiresAt', b.expires_at,
        'totalAmount', COALESCE(SUM(bi.fare_amount), 0),
        'replayed', p_replayed,
        'items', COALESCE(
            jsonb_agg(
                jsonb_build_object(
                    'bookingItemId', bi.booking_item_id,
                    'passengerId', bi.passenger_id,
                    'scheduleId', os.schedule_id,
                    'trainNumber', tr.train_number,
                    'originStopId', bi.origin_stop_id,
                    'destinationStopId', bi.destination_stop_id,
                    'fareType', bi.fare_type,
                    'fareAmount', bi.fare_amount,
                    'seatId', bi.seat_id,
                    'carriageNumber', s.carriage_number,
                    'seatNumber', s.seat_number,
                    'seatType', s.seat_type,
                    'seatPosition', s.seat_position
                ) ORDER BY bi.booking_item_id
            ) FILTER (WHERE bi.booking_item_id IS NOT NULL),
            '[]'::jsonb
        )
    )
      FROM bookings AS b
      LEFT JOIN booking_items AS bi ON bi.booking_id = b.booking_id
      LEFT JOIN seats AS s ON s.seat_id = bi.seat_id
      LEFT JOIN train_stops AS os ON os.stop_id = bi.origin_stop_id
      LEFT JOIN train_schedules AS ts ON ts.schedule_id = os.schedule_id
      LEFT JOIN trains AS tr ON tr.train_id = ts.train_id
     WHERE b.booking_id = p_booking_id
     GROUP BY b.booking_id;
$$;

CREATE OR REPLACE FUNCTION create_booking(
    p_idempotency_key uuid,
    p_journeys jsonb,
    p_tickets jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_user_id             uuid := auth.uid();
    v_member_id           bigint;
    v_booking_id          bigint;
    v_booking_number      text;
    v_schedule_id         bigint;
    v_train_id            bigint;
    v_origin_stop_id      bigint;
    v_destination_stop_id bigint;
    v_origin_order        smallint;
    v_destination_order   smallint;
    v_origin_station_id   bigint;
    v_destination_station_id bigint;
    v_departure_at        timestamptz;
    v_seat_type           thsr_seat_type;
    v_seat_preference     text;
    v_seat_id             bigint;
    v_passenger_id        bigint;
    v_passenger_type      thsr_passenger_type;
    v_student_verified_until date;
    v_fare_type           thsr_fare_type;
    v_fare_amount         numeric(10, 2);
    v_journey             jsonb;
    v_ticket              jsonb;
    v_journey_count       integer;
    v_ticket_count        integer;
BEGIN
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'AUTH_REQUIRED';
    END IF;
    IF p_idempotency_key IS NULL THEN
        RAISE EXCEPTION 'INVALID_IDEMPOTENCY_KEY';
    END IF;
    IF jsonb_typeof(p_journeys) <> 'array' OR jsonb_typeof(p_tickets) <> 'array' THEN
        RAISE EXCEPTION 'INVALID_BOOKING_PAYLOAD';
    END IF;

    v_journey_count := jsonb_array_length(p_journeys);
    v_ticket_count := jsonb_array_length(p_tickets);
    IF v_journey_count NOT BETWEEN 1 AND 2 OR v_ticket_count NOT BETWEEN 1 AND 10
       OR (v_journey_count = 2 AND v_ticket_count > 5) THEN
        RAISE EXCEPTION 'INVALID_BOOKING_LIMITS';
    END IF;
    IF (
        SELECT count(DISTINCT value ->> 'passengerId')
          FROM jsonb_array_elements(p_tickets)
    ) <> v_ticket_count THEN
        RAISE EXCEPTION 'INVALID_DUPLICATE_PASSENGER';
    END IF;
    IF (
        SELECT count(DISTINCT concat_ws(':', value ->> 'scheduleId', value ->> 'originStopId', value ->> 'destinationStopId'))
          FROM jsonb_array_elements(p_journeys)
    ) <> v_journey_count THEN
        RAISE EXCEPTION 'INVALID_DUPLICATE_JOURNEY';
    END IF;

    SELECT member_id INTO v_member_id
      FROM members
     WHERE auth_user_id = v_user_id;
    IF v_member_id IS NULL THEN
        RAISE EXCEPTION 'MEMBER_PROFILE_REQUIRED';
    END IF;

    -- Serialize identical submissions before checking for an existing booking.
    PERFORM pg_advisory_xact_lock(hashtextextended(v_user_id::text || ':' || p_idempotency_key::text, 0));
    SELECT booking_id INTO v_booking_id
      FROM bookings
     WHERE member_id = v_member_id
       AND idempotency_key = p_idempotency_key;
    IF v_booking_id IS NOT NULL THEN
        RETURN build_booking_response(v_booking_id, true);
    END IF;

    -- Always acquire schedule locks in numeric order to prevent deadlocks between
    -- two-leg bookings and serialize seat allocation for a given service.
    FOR v_schedule_id IN
        SELECT DISTINCT (journey.value ->> 'scheduleId')::bigint
          FROM jsonb_array_elements(p_journeys) AS journey
         ORDER BY 1
    LOOP
        PERFORM pg_advisory_xact_lock(v_schedule_id);
    END LOOP;

    -- Release inventory from unpaid expired holds before evaluating availability.
    UPDATE bookings
       SET booking_status = 'CANCELLED'
     WHERE booking_status = 'PENDING'
       AND expires_at <= now();
    DELETE FROM seat_segment_reservations AS ssr
     USING booking_items AS bi, bookings AS b
     WHERE ssr.booking_item_id = bi.booking_item_id
       AND bi.booking_id = b.booking_id
       AND b.booking_status = 'CANCELLED'
       AND b.expires_at <= now();

    v_booking_number := 'HSR'
        || to_char(clock_timestamp() AT TIME ZONE 'Asia/Taipei', 'YYMMDD')
        || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 16));

    INSERT INTO bookings (member_id, booking_number, booking_status, idempotency_key, expires_at)
    VALUES (v_member_id, v_booking_number, 'PENDING', p_idempotency_key, now() + interval '10 minutes')
    RETURNING booking_id INTO v_booking_id;

    FOR v_journey IN SELECT value FROM jsonb_array_elements(p_journeys)
    LOOP
        BEGIN
            v_schedule_id := (v_journey ->> 'scheduleId')::bigint;
            v_origin_stop_id := (v_journey ->> 'originStopId')::bigint;
            v_destination_stop_id := (v_journey ->> 'destinationStopId')::bigint;
            v_seat_type := (v_journey ->> 'seatType')::thsr_seat_type;
            v_seat_preference := upper(v_journey ->> 'seatPreference');
        EXCEPTION WHEN OTHERS THEN
            RAISE EXCEPTION 'INVALID_JOURNEY';
        END;

        IF v_seat_type IS NULL
           OR v_seat_preference IS NULL
           OR v_seat_type NOT IN ('STANDARD', 'BUSINESS')
           OR v_seat_preference NOT IN ('NONE', 'WINDOW', 'AISLE') THEN
            RAISE EXCEPTION 'INVALID_JOURNEY';
        END IF;

        SELECT ts.train_id,
               os.stop_order,
               ds.stop_order,
               os.station_id,
               ds.station_id,
               os.departure_at
          INTO v_train_id,
               v_origin_order,
               v_destination_order,
               v_origin_station_id,
               v_destination_station_id,
               v_departure_at
          FROM train_schedules AS ts
          JOIN train_stops AS os
            ON os.schedule_id = ts.schedule_id AND os.stop_id = v_origin_stop_id
          JOIN train_stops AS ds
            ON ds.schedule_id = ts.schedule_id AND ds.stop_id = v_destination_stop_id
         WHERE ts.schedule_id = v_schedule_id
           AND ts.status = 'SCHEDULED';

        IF NOT FOUND OR v_origin_order >= v_destination_order THEN
            RAISE EXCEPTION 'INVALID_JOURNEY';
        END IF;
        IF v_departure_at < now() + interval '1 hour' THEN
            RAISE EXCEPTION 'BOOKING_WINDOW_CLOSED';
        END IF;
        IF (v_departure_at AT TIME ZONE 'Asia/Taipei')::date
           > (now() AT TIME ZONE 'Asia/Taipei')::date + 28 THEN
            RAISE EXCEPTION 'INVALID_JOURNEY_DATE';
        END IF;

        FOR v_ticket IN SELECT value FROM jsonb_array_elements(p_tickets)
        LOOP
            BEGIN
                v_passenger_id := (v_ticket ->> 'passengerId')::bigint;
                v_fare_type := CASE v_ticket ->> 'ticketType'
                    WHEN 'adult' THEN 'FULL'::thsr_fare_type
                    WHEN 'child' THEN 'CHILD'::thsr_fare_type
                    WHEN 'disabled' THEN 'DISABLED'::thsr_fare_type
                    WHEN 'senior' THEN 'SENIOR'::thsr_fare_type
                    WHEN 'student' THEN 'STUDENT'::thsr_fare_type
                    ELSE NULL
                END;
            EXCEPTION WHEN OTHERS THEN
                RAISE EXCEPTION 'INVALID_TICKET';
            END;

            SELECT passenger_type, student_verified_until
              INTO v_passenger_type, v_student_verified_until
              FROM passengers
             WHERE passenger_id = v_passenger_id
               AND member_id = v_member_id;
            IF NOT FOUND OR v_fare_type IS NULL THEN
                RAISE EXCEPTION 'PASSENGER_NOT_OWNED';
            END IF;
            IF (v_fare_type = 'CHILD' AND v_passenger_type <> 'CHILD')
               OR (v_fare_type = 'SENIOR' AND v_passenger_type <> 'SENIOR')
               OR (v_fare_type = 'DISABLED' AND v_passenger_type <> 'DISABLED')
               OR (
                    v_fare_type = 'STUDENT'
                    AND (
                        v_student_verified_until IS NULL
                        OR v_student_verified_until < (now() AT TIME ZONE 'Asia/Taipei')::date
                    )
               ) THEN
                RAISE EXCEPTION 'INVALID_TICKET_ELIGIBILITY';
            END IF;

            SELECT amount INTO v_fare_amount
              FROM fares
             WHERE origin_station_id = v_origin_station_id
               AND destination_station_id = v_destination_station_id
               AND seat_type = v_seat_type
               AND fare_type = v_fare_type;
            IF v_fare_amount IS NULL THEN
                RAISE EXCEPTION 'FARE_NOT_FOUND';
            END IF;

            SELECT s.seat_id INTO v_seat_id
              FROM seats AS s
             WHERE s.train_id = v_train_id
               AND s.seat_type = v_seat_type
               AND NOT EXISTS (
                    SELECT 1
                      FROM seat_segment_reservations AS ssr
                      JOIN schedule_segments AS sg ON sg.segment_id = ssr.segment_id
                      JOIN train_stops AS fs ON fs.stop_id = sg.from_stop_id
                     WHERE ssr.seat_id = s.seat_id
                       AND fs.schedule_id = v_schedule_id
                       AND fs.stop_order >= v_origin_order
                       AND fs.stop_order < v_destination_order
               )
             ORDER BY
                CASE
                    WHEN v_seat_preference = 'NONE' THEN 0
                    WHEN s.seat_position::text = v_seat_preference THEN 0
                    ELSE 1
                END,
                s.carriage_number,
                s.seat_number
             LIMIT 1
             FOR UPDATE OF s SKIP LOCKED;

            IF v_seat_id IS NULL THEN
                RAISE EXCEPTION 'NO_SEATS_AVAILABLE';
            END IF;

            INSERT INTO booking_items (
                booking_id,
                passenger_id,
                seat_id,
                origin_stop_id,
                destination_stop_id,
                fare_type,
                fare_amount
            ) VALUES (
                v_booking_id,
                v_passenger_id,
                v_seat_id,
                v_origin_stop_id,
                v_destination_stop_id,
                v_fare_type,
                v_fare_amount
            );
        END LOOP;
    END LOOP;

    RETURN build_booking_response(v_booking_id, false);
END;
$$;

CREATE OR REPLACE FUNCTION get_booking(p_booking_number text)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_booking_id bigint;
BEGIN
    IF auth.uid() IS NULL THEN RAISE EXCEPTION 'AUTH_REQUIRED'; END IF;
    SELECT b.booking_id INTO v_booking_id
      FROM bookings AS b
      JOIN members AS m ON m.member_id = b.member_id
     WHERE b.booking_number = p_booking_number
       AND m.auth_user_id = auth.uid();
    IF v_booking_id IS NULL THEN RETURN NULL; END IF;
    RETURN build_booking_response(v_booking_id, false);
END;
$$;

CREATE OR REPLACE FUNCTION cancel_booking(p_booking_number text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_booking_id bigint;
    v_status thsr_booking_status;
BEGIN
    IF auth.uid() IS NULL THEN RAISE EXCEPTION 'AUTH_REQUIRED'; END IF;

    SELECT b.booking_id, b.booking_status
      INTO v_booking_id, v_status
      FROM bookings AS b
      JOIN members AS m ON m.member_id = b.member_id
     WHERE b.booking_number = p_booking_number
       AND m.auth_user_id = auth.uid()
     FOR UPDATE OF b;

    IF v_booking_id IS NULL THEN RAISE EXCEPTION 'BOOKING_NOT_FOUND'; END IF;
    IF v_status = 'CANCELLED' THEN RETURN build_booking_response(v_booking_id, true); END IF;
    IF v_status <> 'PENDING' THEN RAISE EXCEPTION 'BOOKING_CLOSED'; END IF;

    DELETE FROM seat_segment_reservations AS ssr
     USING booking_items AS bi
     WHERE ssr.booking_item_id = bi.booking_item_id
       AND bi.booking_id = v_booking_id;
    UPDATE bookings SET booking_status = 'CANCELLED' WHERE booking_id = v_booking_id;

    RETURN build_booking_response(v_booking_id, false);
END;
$$;

REVOKE ALL ON FUNCTION build_booking_response(bigint, boolean) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION create_booking(uuid, jsonb, jsonb) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION get_booking(text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION cancel_booking(text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION create_booking(uuid, jsonb, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION get_booking(text) TO authenticated;
GRANT EXECUTE ON FUNCTION cancel_booking(text) TO authenticated;

-- ============================================================================
-- 會員建立與乘客結帳 API
-- ============================================================================

CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_name text := nullif(trim(COALESCE(NEW.raw_user_meta_data ->> 'name', '')), '');
BEGIN
    IF NEW.email IS NULL THEN
        RETURN NEW;
    END IF;

    UPDATE public.members
       SET auth_user_id = NEW.id,
           name = COALESCE(v_name, name),
           password_hash = '$supabase-auth$'
     WHERE lower(email) = lower(NEW.email)
       AND auth_user_id IS NULL;

    IF NOT FOUND THEN
        INSERT INTO public.members (name, email, password_hash, auth_user_id)
        VALUES (
            COALESCE(v_name, split_part(NEW.email, '@', 1)),
            lower(NEW.email),
            '$supabase-auth$',
            NEW.id
        )
        ON CONFLICT (email) DO UPDATE
        SET auth_user_id = EXCLUDED.auth_user_id,
            name = COALESCE(v_name, public.members.name),
            password_hash = '$supabase-auth$'
        WHERE public.members.auth_user_id IS NULL
           OR public.members.auth_user_id = EXCLUDED.auth_user_id;
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_auth_user();

-- Link pre-existing Supabase Auth users by e-mail, then create missing profiles.
UPDATE public.members AS m
   SET auth_user_id = u.id,
       password_hash = '$supabase-auth$'
  FROM auth.users AS u
 WHERE u.email IS NOT NULL
   AND lower(m.email) = lower(u.email)
   AND m.auth_user_id IS NULL;

INSERT INTO public.members (name, email, password_hash, auth_user_id)
SELECT
    COALESCE(
        nullif(trim(u.raw_user_meta_data ->> 'name'), ''),
        split_part(u.email, '@', 1)
    ),
    lower(u.email),
    '$supabase-auth$',
    u.id
FROM auth.users AS u
WHERE u.email IS NOT NULL
  AND NOT EXISTS (
      SELECT 1
        FROM public.members AS m
       WHERE m.auth_user_id = u.id
          OR lower(m.email) = lower(u.email)
  );

CREATE OR REPLACE FUNCTION public.ensure_member_profile(p_name text DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_user_id uuid := auth.uid();
    v_email text := lower(auth.jwt() ->> 'email');
    v_member public.members%ROWTYPE;
    v_name text := nullif(trim(COALESCE(p_name, '')), '');
BEGIN
    IF v_user_id IS NULL OR v_email IS NULL THEN
        RAISE EXCEPTION 'AUTH_REQUIRED';
    END IF;

    UPDATE public.members
       SET auth_user_id = v_user_id,
           name = COALESCE(v_name, name),
           password_hash = '$supabase-auth$'
     WHERE lower(email) = v_email
       AND (auth_user_id IS NULL OR auth_user_id = v_user_id)
    RETURNING * INTO v_member;

    IF v_member.member_id IS NULL THEN
        INSERT INTO public.members (name, email, password_hash, auth_user_id)
        VALUES (
            COALESCE(v_name, split_part(v_email, '@', 1)),
            v_email,
            '$supabase-auth$',
            v_user_id
        )
        RETURNING * INTO v_member;
    END IF;

    RETURN jsonb_build_object(
        'memberId', v_member.member_id,
        'name', v_member.name,
        'email', v_member.email
    );
END;
$$;

CREATE OR REPLACE FUNCTION public.list_my_passengers()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_member_id bigint;
BEGIN
    IF auth.uid() IS NULL THEN
        RAISE EXCEPTION 'AUTH_REQUIRED';
    END IF;

    SELECT member_id INTO v_member_id
      FROM public.members
     WHERE auth_user_id = auth.uid();

    IF v_member_id IS NULL THEN
        RAISE EXCEPTION 'MEMBER_PROFILE_REQUIRED';
    END IF;

    RETURN (
        SELECT COALESCE(
            jsonb_agg(
                jsonb_build_object(
                    'passengerId', p.passenger_id,
                    'name', p.name,
                    'idNumberMasked',
                        CASE
                            WHEN length(p.id_number) <= 4 THEN repeat('*', length(p.id_number))
                            ELSE left(p.id_number, 2)
                                || repeat('*', greatest(length(p.id_number) - 4, 1))
                                || right(p.id_number, 2)
                        END,
                    'passengerType', p.passenger_type,
                    'studentVerifiedUntil', p.student_verified_until
                ) ORDER BY p.created_at, p.passenger_id
            ),
            '[]'::jsonb
        )
          FROM public.passengers AS p
         WHERE p.member_id = v_member_id
    );
END;
$$;

CREATE OR REPLACE FUNCTION public.create_my_passenger(
    p_name text,
    p_id_number text,
    p_passenger_type text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_member_id bigint;
    v_passenger public.passengers%ROWTYPE;
    v_name text := trim(COALESCE(p_name, ''));
    v_id_number text := upper(trim(COALESCE(p_id_number, '')));
    v_type thsr_passenger_type;
BEGIN
    IF auth.uid() IS NULL THEN
        RAISE EXCEPTION 'AUTH_REQUIRED';
    END IF;
    IF length(v_name) NOT BETWEEN 1 AND 100
       OR length(v_id_number) NOT BETWEEN 6 AND 32
       OR v_id_number !~ '^[A-Z0-9-]+$' THEN
        RAISE EXCEPTION 'INVALID_PASSENGER';
    END IF;

    BEGIN
        v_type := upper(p_passenger_type)::thsr_passenger_type;
    EXCEPTION WHEN OTHERS THEN
        RAISE EXCEPTION 'INVALID_PASSENGER';
    END;

    SELECT member_id INTO v_member_id
      FROM public.members
     WHERE auth_user_id = auth.uid();
    IF v_member_id IS NULL THEN
        RAISE EXCEPTION 'MEMBER_PROFILE_REQUIRED';
    END IF;

    INSERT INTO public.passengers (member_id, name, id_number, passenger_type)
    VALUES (v_member_id, v_name, v_id_number, v_type)
    RETURNING * INTO v_passenger;

    RETURN jsonb_build_object(
        'passengerId', v_passenger.passenger_id,
        'name', v_passenger.name,
        'idNumberMasked',
            CASE
                WHEN length(v_passenger.id_number) <= 4 THEN repeat('*', length(v_passenger.id_number))
                ELSE left(v_passenger.id_number, 2)
                    || repeat('*', greatest(length(v_passenger.id_number) - 4, 1))
                    || right(v_passenger.id_number, 2)
            END,
        'passengerType', v_passenger.passenger_type,
        'studentVerifiedUntil', v_passenger.student_verified_until
    );
END;
$$;

REVOKE ALL ON FUNCTION public.handle_new_auth_user() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.ensure_member_profile(text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.list_my_passengers() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.create_my_passenger(text, text, text) FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.ensure_member_profile(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.list_my_passengers() TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_my_passenger(text, text, text) TO authenticated;

-- ============================================================================
-- 會員訂單查詢與示範付款 API
-- ============================================================================

CREATE OR REPLACE FUNCTION public.build_booking_response(
    p_booking_id bigint,
    p_replayed boolean DEFAULT false
)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
    SELECT jsonb_build_object(
        'bookingId', b.booking_id,
        'bookingNumber', b.booking_number,
        'status', b.booking_status,
        'createdAt', b.created_at,
        'expiresAt', b.expires_at,
        'totalAmount', COALESCE(SUM(bi.fare_amount), 0),
        'paymentStatus', (
            SELECT p.payment_status
              FROM public.payments AS p
             WHERE p.booking_id = b.booking_id
             ORDER BY p.created_at DESC, p.payment_id DESC
             LIMIT 1
        ),
        'paidAt', (
            SELECT p.paid_at
              FROM public.payments AS p
             WHERE p.booking_id = b.booking_id
               AND p.payment_status = 'PAID'
             ORDER BY p.paid_at DESC
             LIMIT 1
        ),
        'replayed', p_replayed,
        'items', COALESCE(
            jsonb_agg(
                jsonb_build_object(
                    'bookingItemId', bi.booking_item_id,
                    'passengerId', bi.passenger_id,
                    'scheduleId', os.schedule_id,
                    'trainNumber', tr.train_number,
                    'originStopId', bi.origin_stop_id,
                    'destinationStopId', bi.destination_stop_id,
                    'fareType', bi.fare_type,
                    'fareAmount', bi.fare_amount,
                    'seatId', bi.seat_id,
                    'carriageNumber', s.carriage_number,
                    'seatNumber', s.seat_number,
                    'seatType', s.seat_type,
                    'seatPosition', s.seat_position,
                    'ticketNumber', tk.ticket_number,
                    'ticketStatus', tk.status
                ) ORDER BY bi.booking_item_id
            ) FILTER (WHERE bi.booking_item_id IS NOT NULL),
            '[]'::jsonb
        )
    )
      FROM public.bookings AS b
      LEFT JOIN public.booking_items AS bi ON bi.booking_id = b.booking_id
      LEFT JOIN public.seats AS s ON s.seat_id = bi.seat_id
      LEFT JOIN public.train_stops AS os ON os.stop_id = bi.origin_stop_id
      LEFT JOIN public.train_schedules AS ts ON ts.schedule_id = os.schedule_id
      LEFT JOIN public.trains AS tr ON tr.train_id = ts.train_id
      LEFT JOIN public.tickets AS tk ON tk.booking_item_id = bi.booking_item_id
     WHERE b.booking_id = p_booking_id
     GROUP BY b.booking_id;
$$;

CREATE OR REPLACE FUNCTION public.list_my_bookings()
RETURNS jsonb
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_member_id bigint;
    v_result jsonb;
BEGIN
    IF auth.uid() IS NULL THEN
        RAISE EXCEPTION 'AUTH_REQUIRED';
    END IF;

    SELECT member_id INTO v_member_id
      FROM public.members
     WHERE auth_user_id = auth.uid();
    IF v_member_id IS NULL THEN
        RAISE EXCEPTION 'MEMBER_PROFILE_REQUIRED';
    END IF;

    UPDATE public.bookings
       SET booking_status = 'CANCELLED'
     WHERE member_id = v_member_id
       AND booking_status = 'PENDING'
       AND expires_at <= now();

    DELETE FROM public.seat_segment_reservations AS ssr
     USING public.booking_items AS bi, public.bookings AS b
     WHERE ssr.booking_item_id = bi.booking_item_id
       AND bi.booking_id = b.booking_id
       AND b.member_id = v_member_id
       AND b.booking_status = 'CANCELLED'
       AND b.expires_at <= now();

    SELECT COALESCE(
        jsonb_agg(
            jsonb_build_object(
                'bookingNumber', b.booking_number,
                'status', b.booking_status,
                'createdAt', b.created_at,
                'expiresAt', b.expires_at,
                'totalAmount', (
                    SELECT COALESCE(SUM(bi.fare_amount), 0)
                      FROM public.booking_items AS bi
                     WHERE bi.booking_id = b.booking_id
                ),
                'itemCount', (
                    SELECT COUNT(*)
                      FROM public.booking_items AS bi
                     WHERE bi.booking_id = b.booking_id
                ),
                'journeys', (
                    SELECT COALESCE(
                        jsonb_agg(
                            jsonb_build_object(
                                'scheduleId', j.schedule_id,
                                'trainNumber', j.train_number,
                                'originName', j.origin_name,
                                'destinationName', j.destination_name,
                                'departureAt', j.departure_at,
                                'arrivalAt', j.arrival_at
                            ) ORDER BY j.departure_at
                        ),
                        '[]'::jsonb
                    )
                      FROM (
                          SELECT DISTINCT
                              os.schedule_id,
                              tr.train_number,
                              origin.station_name AS origin_name,
                              destination.station_name AS destination_name,
                              os.departure_at,
                              ds.arrival_at
                            FROM public.booking_items AS bi
                            JOIN public.train_stops AS os ON os.stop_id = bi.origin_stop_id
                            JOIN public.train_stops AS ds ON ds.stop_id = bi.destination_stop_id
                            JOIN public.train_schedules AS ts ON ts.schedule_id = os.schedule_id
                            JOIN public.trains AS tr ON tr.train_id = ts.train_id
                            JOIN public.stations AS origin ON origin.station_id = os.station_id
                            JOIN public.stations AS destination ON destination.station_id = ds.station_id
                           WHERE bi.booking_id = b.booking_id
                      ) AS j
                )
            ) ORDER BY b.created_at DESC, b.booking_id DESC
        ),
        '[]'::jsonb
    ) INTO v_result
      FROM public.bookings AS b
      JOIN public.members AS m ON m.member_id = b.member_id
     WHERE m.auth_user_id = auth.uid();

    RETURN v_result;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_booking(p_booking_number text)
RETURNS jsonb
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_booking_id bigint;
    v_status thsr_booking_status;
    v_expires_at timestamptz;
BEGIN
    IF auth.uid() IS NULL THEN
        RAISE EXCEPTION 'AUTH_REQUIRED';
    END IF;

    SELECT b.booking_id, b.booking_status, b.expires_at
      INTO v_booking_id, v_status, v_expires_at
      FROM public.bookings AS b
      JOIN public.members AS m ON m.member_id = b.member_id
     WHERE b.booking_number = p_booking_number
       AND m.auth_user_id = auth.uid()
     FOR UPDATE OF b;

    IF v_booking_id IS NULL THEN
        RETURN NULL;
    END IF;

    IF v_status = 'PENDING' AND v_expires_at <= now() THEN
        DELETE FROM public.seat_segment_reservations AS ssr
         USING public.booking_items AS bi
         WHERE ssr.booking_item_id = bi.booking_item_id
           AND bi.booking_id = v_booking_id;
        UPDATE public.bookings
           SET booking_status = 'CANCELLED'
         WHERE booking_id = v_booking_id;
    END IF;

    RETURN public.build_booking_response(v_booking_id, false);
END;
$$;

CREATE OR REPLACE FUNCTION public.simulate_booking_payment(
    p_booking_number text,
    p_payment_method text DEFAULT 'CREDIT_CARD'
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_booking_id bigint;
    v_status thsr_booking_status;
    v_expires_at timestamptz;
    v_amount numeric(10, 2);
    v_method thsr_payment_method;
    v_transaction_id text;
BEGIN
    IF auth.uid() IS NULL THEN
        RAISE EXCEPTION 'AUTH_REQUIRED';
    END IF;

    BEGIN
        v_method := upper(p_payment_method)::thsr_payment_method;
    EXCEPTION WHEN OTHERS THEN
        RAISE EXCEPTION 'INVALID_PAYMENT_METHOD';
    END;

    SELECT b.booking_id, b.booking_status, b.expires_at
      INTO v_booking_id, v_status, v_expires_at
      FROM public.bookings AS b
      JOIN public.members AS m ON m.member_id = b.member_id
     WHERE b.booking_number = p_booking_number
       AND m.auth_user_id = auth.uid()
     FOR UPDATE OF b;

    IF v_booking_id IS NULL THEN
        RAISE EXCEPTION 'BOOKING_NOT_FOUND';
    END IF;
    IF v_status = 'CONFIRMED' THEN
        RETURN public.build_booking_response(v_booking_id, true);
    END IF;
    IF v_status <> 'PENDING' THEN
        RAISE EXCEPTION 'BOOKING_CLOSED';
    END IF;

    IF v_expires_at <= now() THEN
        DELETE FROM public.seat_segment_reservations AS ssr
         USING public.booking_items AS bi
         WHERE ssr.booking_item_id = bi.booking_item_id
           AND bi.booking_id = v_booking_id;
        UPDATE public.bookings
           SET booking_status = 'CANCELLED'
         WHERE booking_id = v_booking_id;
        RETURN public.build_booking_response(v_booking_id, false);
    END IF;

    SELECT SUM(fare_amount)
      INTO v_amount
      FROM public.booking_items
     WHERE booking_id = v_booking_id;
    IF v_amount IS NULL OR v_amount <= 0 THEN
        RAISE EXCEPTION 'INVALID_PAYMENT_AMOUNT';
    END IF;

    v_transaction_id := 'DEMO-'
        || to_char(clock_timestamp() AT TIME ZONE 'Asia/Taipei', 'YYYYMMDDHH24MISS')
        || '-'
        || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 12));

    INSERT INTO public.payments (
        booking_id,
        amount,
        payment_method,
        payment_status,
        transaction_id,
        paid_at
    ) VALUES (
        v_booking_id,
        v_amount,
        v_method,
        'PAID',
        v_transaction_id,
        now()
    );

    UPDATE public.bookings
       SET booking_status = 'CONFIRMED'
     WHERE booking_id = v_booking_id;

    INSERT INTO public.tickets (booking_item_id, ticket_number, status)
    SELECT
        bi.booking_item_id,
        'TKT' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 20)),
        'ISSUED'
      FROM public.booking_items AS bi
     WHERE bi.booking_id = v_booking_id
    ON CONFLICT (booking_item_id) DO NOTHING;

    RETURN public.build_booking_response(v_booking_id, false);
END;
$$;

REVOKE ALL ON FUNCTION public.list_my_bookings() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.get_booking(text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.simulate_booking_payment(text, text) FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.list_my_bookings() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_booking(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.simulate_booking_payment(text, text) TO authenticated;

-- ============================================================================
-- 會員資料唯一來源
-- ============================================================================

CREATE OR REPLACE FUNCTION public.ensure_member_profile(p_name text DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_user_id uuid := auth.uid();
    v_email text := lower(auth.jwt() ->> 'email');
    v_member public.members%ROWTYPE;
    v_name text := nullif(trim(COALESCE(p_name, '')), '');
BEGIN
    IF v_user_id IS NULL OR v_email IS NULL THEN
        RAISE EXCEPTION 'AUTH_REQUIRED';
    END IF;

    UPDATE public.members
       SET auth_user_id = v_user_id,
           password_hash = '$supabase-auth$'
     WHERE lower(email) = v_email
       AND (auth_user_id IS NULL OR auth_user_id = v_user_id)
    RETURNING * INTO v_member;

    IF v_member.member_id IS NULL THEN
        INSERT INTO public.members (name, email, password_hash, auth_user_id)
        VALUES (
            COALESCE(v_name, split_part(v_email, '@', 1)),
            v_email,
            '$supabase-auth$',
            v_user_id
        )
        RETURNING * INTO v_member;
    END IF;

    RETURN jsonb_build_object(
        'memberId', v_member.member_id,
        'name', v_member.name,
        'email', v_member.email
    );
END;
$$;

CREATE OR REPLACE FUNCTION public.get_my_member_profile()
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
    SELECT jsonb_build_object(
        'memberId', m.member_id,
        'name', m.name,
        'email', m.email
    )
      FROM public.members AS m
     WHERE m.auth_user_id = auth.uid();
$$;

REVOKE ALL ON FUNCTION public.ensure_member_profile(text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.get_my_member_profile() FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.ensure_member_profile(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_my_member_profile() TO authenticated;

COMMIT;

