-- ============================================================================
-- 既有 Supabase 資料庫升級：學生票與票價主檔
--
-- 適用於已經執行過 thsr_booking_supabase.sql 的資料庫。
-- 本檔執行完成並 commit 後，再執行 seed_demo_data.sql。
-- ============================================================================

BEGIN;

SET search_path TO public;

ALTER TYPE thsr_fare_type ADD VALUE IF NOT EXISTS 'STUDENT';

CREATE TABLE IF NOT EXISTS fares (
    fare_id                 bigint GENERATED BY DEFAULT AS IDENTITY,
    origin_station_id       bigint NOT NULL,
    destination_station_id  bigint NOT NULL,
    seat_type               thsr_seat_type NOT NULL,
    fare_type               thsr_fare_type NOT NULL,
    amount                  numeric(10, 2) NOT NULL,
    CONSTRAINT pk_fares PRIMARY KEY (fare_id),
    CONSTRAINT uq_fares_route_seat_type
        UNIQUE (
            origin_station_id,
            destination_station_id,
            seat_type,
            fare_type
        ),
    CONSTRAINT ck_fares_distinct_stations CHECK (
        origin_station_id <> destination_station_id
    ),
    CONSTRAINT ck_fares_amount_positive CHECK (amount > 0),
    CONSTRAINT fk_fares_origin_station
        FOREIGN KEY (origin_station_id) REFERENCES stations (station_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_fares_destination_station
        FOREIGN KEY (destination_station_id) REFERENCES stations (station_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

COMMENT ON TABLE fares IS '現行票價主檔；依起迄站、座位類型與票種定價';
COMMENT ON COLUMN fares.amount IS '用於報價；訂票後的成交價另存於 booking_items.fare_amount';

COMMIT;
