-- ============================================================================
-- 高鐵訂票系統：3NF 修正版資料庫結構
-- 適用：Supabase / PostgreSQL 15 以上
--
-- 使用方式：
-- 1. 直接在 Supabase SQL Editor 執行本檔，不需要 CREATE DATABASE 或 USE。
-- 2. 建議在尚未建立同名資料表的專案中執行一次。
-- 3. 全部 DDL 包在同一個交易中；任一步驟失敗時，不會留下半套結構。
--
-- 設計重點：
-- 1. booking_items 不重複保存 schedule_id；班次可由起訖停靠點決定。
-- 2. schedule_segments 明確表示兩個相鄰停靠點之間的行車區間。
-- 3. seat_segment_reservations 以「區間 + 座位」為主鍵，防止重複售票。
-- 4. 票種與成交票價只保存在 booking_items；tickets 不再重複保存。
-- 5. 訂單總額由 v_booking_totals 即時計算，避免 total_amount 更新異常。
-- 6. fares 保存起迄站、座位類型與票種的現行售價。
-- 7. seats 明確保存座位位置，不由應用程式依座號推測靠窗或走道。
-- ============================================================================

BEGIN;

SET search_path TO public;

-- ----------------------------------------------------------------------------
-- 列舉型別
-- PostgreSQL 沒有 MySQL 的欄位內 ENUM 語法，因此先建立命名型別。
-- duplicate_object 例外處理讓已存在的相同型別可以被沿用。
-- ----------------------------------------------------------------------------

DO $$
BEGIN
    CREATE TYPE thsr_passenger_type AS ENUM (
        'ADULT', 'CHILD', 'SENIOR', 'DISABLED'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
    CREATE TYPE thsr_seat_type AS ENUM (
        'STANDARD', 'BUSINESS', 'ACCESSIBLE'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
    CREATE TYPE thsr_seat_position AS ENUM (
        'WINDOW', 'AISLE', 'MIDDLE'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
    CREATE TYPE thsr_schedule_status AS ENUM (
        'SCHEDULED', 'BOARDING', 'DEPARTED', 'ARRIVED', 'CANCELLED'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
    CREATE TYPE thsr_booking_status AS ENUM (
        'PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
    CREATE TYPE thsr_fare_type AS ENUM (
        'FULL', 'CHILD', 'SENIOR', 'DISABLED', 'STUDENT', 'EARLY_BIRD'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
    CREATE TYPE thsr_payment_method AS ENUM (
        'CREDIT_CARD', 'ATM', 'CONVENIENCE_STORE', 'MOBILE_PAYMENT'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
    CREATE TYPE thsr_payment_status AS ENUM (
        'PENDING', 'PAID', 'FAILED', 'REFUNDED'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
    CREATE TYPE thsr_ticket_status AS ENUM (
        'ISSUED', 'USED', 'CANCELLED'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END;
$$;

-- ----------------------------------------------------------------------------
-- 會員與乘客
-- ----------------------------------------------------------------------------

CREATE TABLE members (
    member_id      bigint GENERATED BY DEFAULT AS IDENTITY,
    name           varchar(100) NOT NULL,
    email          varchar(254) NOT NULL,
    phone          varchar(20),
    password_hash  varchar(255) NOT NULL,
    created_at     timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_members PRIMARY KEY (member_id),
    CONSTRAINT uq_members_email UNIQUE (email),
    CONSTRAINT uq_members_phone UNIQUE (phone)
);

COMMENT ON TABLE members IS '會員';
COMMENT ON COLUMN members.member_id IS '會員流水號';
COMMENT ON COLUMN members.password_hash IS '密碼雜湊；不可存明文密碼';

CREATE TABLE passengers (
    passenger_id    bigint GENERATED BY DEFAULT AS IDENTITY,
    member_id       bigint NOT NULL,
    name            varchar(100) NOT NULL,
    id_number       varchar(32) NOT NULL,
    passenger_type  thsr_passenger_type NOT NULL DEFAULT 'ADULT',
    created_at      timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_passengers PRIMARY KEY (passenger_id),
    CONSTRAINT uq_passengers_member_document UNIQUE (member_id, id_number),
    CONSTRAINT fk_passengers_member
        FOREIGN KEY (member_id) REFERENCES members (member_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

COMMENT ON TABLE passengers IS '會員保存的乘客資料';
COMMENT ON COLUMN passengers.id_number IS '證件號碼；正式系統應加密或代碼化';

-- ----------------------------------------------------------------------------
-- 列車、座位、車站與每日班次
-- ----------------------------------------------------------------------------

CREATE TABLE trains (
    train_id      bigint GENERATED BY DEFAULT AS IDENTITY,
    train_number  varchar(10) NOT NULL,
    train_type    varchar(50) NOT NULL,
    CONSTRAINT pk_trains PRIMARY KEY (train_id),
    CONSTRAINT uq_trains_number UNIQUE (train_number)
);

COMMENT ON TABLE trains IS '列車／車次主檔';

CREATE TABLE seats (
    seat_id          bigint GENERATED BY DEFAULT AS IDENTITY,
    train_id         bigint NOT NULL,
    carriage_number  smallint NOT NULL,
    seat_number      varchar(5) NOT NULL,
    seat_type        thsr_seat_type NOT NULL DEFAULT 'STANDARD',
    seat_position    thsr_seat_position NOT NULL,
    CONSTRAINT pk_seats PRIMARY KEY (seat_id),
    CONSTRAINT uq_seats_train_position
        UNIQUE (train_id, carriage_number, seat_number),
    CONSTRAINT ck_seats_carriage_positive CHECK (carriage_number > 0),
    CONSTRAINT fk_seats_train
        FOREIGN KEY (train_id) REFERENCES trains (train_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

COMMENT ON TABLE seats IS '列車座位';
COMMENT ON COLUMN seats.seat_position IS '座位位置：靠窗、走道或中間座位';

CREATE INDEX idx_seats_train_type_position
    ON seats (train_id, seat_type, seat_position);

CREATE TABLE stations (
    station_id       bigint GENERATED BY DEFAULT AS IDENTITY,
    station_code     varchar(10) NOT NULL,
    station_name     varchar(100) NOT NULL,
    station_name_en  varchar(100) NOT NULL,
    city             varchar(100) NOT NULL,
    station_order    smallint NOT NULL,
    CONSTRAINT pk_stations PRIMARY KEY (station_id),
    CONSTRAINT uq_stations_code UNIQUE (station_code),
    CONSTRAINT uq_stations_order UNIQUE (station_order),
    CONSTRAINT ck_stations_order_positive CHECK (station_order > 0)
);

COMMENT ON TABLE stations IS '車站';

CREATE TABLE fares (
    fare_id                 bigint GENERATED BY DEFAULT AS IDENTITY,
    origin_station_id       bigint NOT NULL,
    destination_station_id  bigint NOT NULL,
    seat_type               thsr_seat_type NOT NULL,
    fare_type               thsr_fare_type NOT NULL,
    amount                  numeric(10, 2) NOT NULL,
    CONSTRAINT pk_fares PRIMARY KEY (fare_id),
    CONSTRAINT uq_fares_route_seat_type
        UNIQUE (
            origin_station_id,
            destination_station_id,
            seat_type,
            fare_type
        ),
    CONSTRAINT ck_fares_distinct_stations CHECK (
        origin_station_id <> destination_station_id
    ),
    CONSTRAINT ck_fares_amount_positive CHECK (amount > 0),
    CONSTRAINT fk_fares_origin_station
        FOREIGN KEY (origin_station_id) REFERENCES stations (station_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_fares_destination_station
        FOREIGN KEY (destination_station_id) REFERENCES stations (station_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

COMMENT ON TABLE fares IS '現行票價主檔；依起迄站、座位類型與票種定價';
COMMENT ON COLUMN fares.amount IS '用於報價；訂票後的成交價另存於 booking_items.fare_amount';

CREATE TABLE train_schedules (
    schedule_id  bigint GENERATED BY DEFAULT AS IDENTITY,
    train_id     bigint NOT NULL,
    service_date date NOT NULL,
    status       thsr_schedule_status NOT NULL DEFAULT 'SCHEDULED',
    CONSTRAINT pk_train_schedules PRIMARY KEY (schedule_id),
    CONSTRAINT uq_train_schedules_train_date UNIQUE (train_id, service_date),
    CONSTRAINT fk_train_schedules_train
        FOREIGN KEY (train_id) REFERENCES trains (train_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

COMMENT ON TABLE train_schedules IS '每日實際行駛班次';

CREATE TABLE train_stops (
    stop_id        bigint GENERATED BY DEFAULT AS IDENTITY,
    schedule_id    bigint NOT NULL,
    station_id     bigint NOT NULL,
    stop_order     smallint NOT NULL,
    arrival_at     timestamptz,
    departure_at   timestamptz,
    CONSTRAINT pk_train_stops PRIMARY KEY (stop_id),
    CONSTRAINT uq_train_stops_schedule_order UNIQUE (schedule_id, stop_order),
    CONSTRAINT uq_train_stops_schedule_station UNIQUE (schedule_id, station_id),
    CONSTRAINT ck_train_stops_order_positive CHECK (stop_order > 0),
    CONSTRAINT ck_train_stops_time_order CHECK (
        arrival_at IS NULL
        OR departure_at IS NULL
        OR arrival_at <= departure_at
    ),
    CONSTRAINT fk_train_stops_schedule
        FOREIGN KEY (schedule_id) REFERENCES train_schedules (schedule_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_train_stops_station
        FOREIGN KEY (station_id) REFERENCES stations (station_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

COMMENT ON TABLE train_stops IS '某一每日班次的停靠站與時刻';

CREATE TABLE schedule_segments (
    segment_id    bigint GENERATED BY DEFAULT AS IDENTITY,
    from_stop_id  bigint NOT NULL,
    to_stop_id    bigint NOT NULL,
    CONSTRAINT pk_schedule_segments PRIMARY KEY (segment_id),
    -- 每一停靠點最多只會接出／接入一個相鄰區間，因此兩者都是候選鍵。
    CONSTRAINT uq_schedule_segments_from_stop UNIQUE (from_stop_id),
    CONSTRAINT uq_schedule_segments_to_stop UNIQUE (to_stop_id),
    CONSTRAINT ck_schedule_segments_distinct_stops
        CHECK (from_stop_id <> to_stop_id),
    CONSTRAINT fk_schedule_segments_from_stop
        FOREIGN KEY (from_stop_id) REFERENCES train_stops (stop_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_schedule_segments_to_stop
        FOREIGN KEY (to_stop_id) REFERENCES train_stops (stop_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

COMMENT ON TABLE schedule_segments IS '同一班次中兩個相鄰停靠點之間的區間';

-- ----------------------------------------------------------------------------
-- 訂單、訂票項目與座位區間鎖定
-- ----------------------------------------------------------------------------

CREATE TABLE bookings (
    booking_id      bigint GENERATED BY DEFAULT AS IDENTITY,
    member_id       bigint NOT NULL,
    booking_number  varchar(30) NOT NULL,
    booking_status  thsr_booking_status NOT NULL DEFAULT 'PENDING',
    created_at      timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_bookings PRIMARY KEY (booking_id),
    CONSTRAINT uq_bookings_number UNIQUE (booking_number),
    CONSTRAINT fk_bookings_member
        FOREIGN KEY (member_id) REFERENCES members (member_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

COMMENT ON TABLE bookings IS '訂單主檔；總額由訂票項目加總取得';

CREATE TABLE booking_items (
    booking_item_id      bigint GENERATED BY DEFAULT AS IDENTITY,
    booking_id           bigint NOT NULL,
    passenger_id         bigint NOT NULL,
    seat_id              bigint NOT NULL,
    origin_stop_id       bigint NOT NULL,
    destination_stop_id  bigint NOT NULL,
    fare_type            thsr_fare_type NOT NULL DEFAULT 'FULL',
    fare_amount          numeric(10, 2) NOT NULL,
    created_at           timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_booking_items PRIMARY KEY (booking_item_id),
    -- 供座位區間表以複合外鍵驗證 booking_item_id 與 seat_id 的一致性。
    CONSTRAINT uq_booking_items_id_seat UNIQUE (booking_item_id, seat_id),
    CONSTRAINT ck_booking_items_distinct_stops CHECK (
        origin_stop_id <> destination_stop_id
    ),
    CONSTRAINT ck_booking_items_fare_nonnegative CHECK (fare_amount >= 0),
    CONSTRAINT fk_booking_items_booking
        FOREIGN KEY (booking_id) REFERENCES bookings (booking_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_booking_items_passenger
        FOREIGN KEY (passenger_id) REFERENCES passengers (passenger_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_booking_items_seat
        FOREIGN KEY (seat_id) REFERENCES seats (seat_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_booking_items_origin_stop
        FOREIGN KEY (origin_stop_id) REFERENCES train_stops (stop_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_booking_items_destination_stop
        FOREIGN KEY (destination_stop_id) REFERENCES train_stops (stop_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

COMMENT ON TABLE booking_items IS '一張訂單中的一位乘客、一段旅程及其成交票價';

CREATE TABLE seat_segment_reservations (
    segment_id      bigint NOT NULL,
    seat_id         bigint NOT NULL,
    booking_item_id bigint NOT NULL,
    reserved_at     timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 同一區間的同一座位只能出現一次，直接阻止重複售票。
    CONSTRAINT pk_seat_segment_reservations PRIMARY KEY (segment_id, seat_id),
    CONSTRAINT uq_seat_segment_booking_item UNIQUE (booking_item_id, segment_id),
    CONSTRAINT fk_seat_segment_segment
        FOREIGN KEY (segment_id) REFERENCES schedule_segments (segment_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_seat_segment_booking_item_seat
        FOREIGN KEY (booking_item_id, seat_id)
        REFERENCES booking_items (booking_item_id, seat_id)
        ON UPDATE RESTRICT ON DELETE CASCADE
);

COMMENT ON TABLE seat_segment_reservations IS '座位在各相鄰站間區間的占用紀錄';

-- ----------------------------------------------------------------------------
-- 付款與票券
-- ----------------------------------------------------------------------------

CREATE TABLE payments (
    payment_id      bigint GENERATED BY DEFAULT AS IDENTITY,
    booking_id      bigint NOT NULL,
    amount          numeric(10, 2) NOT NULL,
    payment_method  thsr_payment_method NOT NULL,
    payment_status  thsr_payment_status NOT NULL DEFAULT 'PENDING',
    transaction_id  varchar(100),
    paid_at         timestamptz,
    created_at      timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_payments PRIMARY KEY (payment_id),
    CONSTRAINT uq_payments_transaction UNIQUE (transaction_id),
    CONSTRAINT ck_payments_amount_positive CHECK (amount > 0),
    CONSTRAINT ck_payments_paid_time CHECK (
        payment_status NOT IN ('PAID', 'REFUNDED') OR paid_at IS NOT NULL
    ),
    CONSTRAINT fk_payments_booking
        FOREIGN KEY (booking_id) REFERENCES bookings (booking_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

COMMENT ON TABLE payments IS '付款嘗試與結果；一張訂單可有多次付款紀錄';

CREATE TABLE tickets (
    ticket_id       bigint GENERATED BY DEFAULT AS IDENTITY,
    booking_item_id bigint NOT NULL,
    ticket_number   varchar(40) NOT NULL,
    status          thsr_ticket_status NOT NULL DEFAULT 'ISSUED',
    issued_at       timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_tickets PRIMARY KEY (ticket_id),
    CONSTRAINT uq_tickets_booking_item UNIQUE (booking_item_id),
    CONSTRAINT uq_tickets_number UNIQUE (ticket_number),
    CONSTRAINT fk_tickets_booking_item
        FOREIGN KEY (booking_item_id) REFERENCES booking_items (booking_item_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

COMMENT ON TABLE tickets IS '已開立票券；票種與成交價由訂票項目取得';

-- ----------------------------------------------------------------------------
-- Supabase Row Level Security
-- 搜尋班次需要公開讀取主檔與時刻表；會員與交易表不開放匿名存取。
-- ----------------------------------------------------------------------------

ALTER TABLE stations ENABLE ROW LEVEL SECURITY;
ALTER TABLE fares ENABLE ROW LEVEL SECURITY;
ALTER TABLE trains ENABLE ROW LEVEL SECURITY;
ALTER TABLE seats ENABLE ROW LEVEL SECURITY;
ALTER TABLE train_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE train_stops ENABLE ROW LEVEL SECURITY;
ALTER TABLE schedule_segments ENABLE ROW LEVEL SECURITY;

CREATE POLICY public_read ON stations
FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY public_read ON fares
FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY public_read ON trains
FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY public_read ON seats
FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY public_read ON train_schedules
FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY public_read ON train_stops
FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY public_read ON schedule_segments
FOR SELECT TO anon, authenticated USING (true);

-- ----------------------------------------------------------------------------
-- 跨資料表商業規則
-- PostgreSQL 使用 PL/pgSQL trigger function，再將 function 綁定到 trigger。
-- ----------------------------------------------------------------------------

-- 驗證行車區間的起訖停靠點屬於同一班次，而且兩站必須相鄰。
CREATE OR REPLACE FUNCTION fn_validate_schedule_segment_insert()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
    v_from_schedule bigint;
    v_to_schedule   bigint;
    v_from_order    smallint;
    v_to_order      smallint;
BEGIN
    SELECT schedule_id, stop_order
      INTO v_from_schedule, v_from_order
      FROM train_stops
     WHERE stop_id = NEW.from_stop_id;

    SELECT schedule_id, stop_order
      INTO v_to_schedule, v_to_order
      FROM train_stops
     WHERE stop_id = NEW.to_stop_id;

    IF v_from_schedule IS DISTINCT FROM v_to_schedule THEN
        RAISE EXCEPTION '區間的起點與終點必須屬於同一班次';
    END IF;

    IF v_to_order IS DISTINCT FROM v_from_order + 1 THEN
        RAISE EXCEPTION '區間的終點必須是起點的下一個停靠站';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER bi_schedule_segments_validate
BEFORE INSERT ON schedule_segments
FOR EACH ROW
EXECUTE FUNCTION fn_validate_schedule_segment_insert();

-- 區間建立後不可改接其他停靠點，以免既有預訂指向錯誤區間。
CREATE OR REPLACE FUNCTION fn_prevent_schedule_segment_endpoint_update()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
    IF NEW.from_stop_id IS DISTINCT FROM OLD.from_stop_id
       OR NEW.to_stop_id IS DISTINCT FROM OLD.to_stop_id THEN
        RAISE EXCEPTION '不可修改既有區間端點；請刪除後重新建立';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER bu_schedule_segments_validate
BEFORE UPDATE ON schedule_segments
FOR EACH ROW
EXECUTE FUNCTION fn_prevent_schedule_segment_endpoint_update();

-- 驗證訂票項目的班次、起訖順序、座位列車、會員與完整區間。
CREATE OR REPLACE FUNCTION fn_validate_booking_item_insert()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
    v_origin_schedule     bigint;
    v_destination_sched  bigint;
    v_origin_order        smallint;
    v_destination_order   smallint;
    v_schedule_train      bigint;
    v_seat_train          bigint;
    v_booking_member      bigint;
    v_passenger_member    bigint;
    v_segment_count       bigint;
BEGIN
    SELECT schedule_id, stop_order
      INTO v_origin_schedule, v_origin_order
      FROM train_stops
     WHERE stop_id = NEW.origin_stop_id;

    SELECT schedule_id, stop_order
      INTO v_destination_sched, v_destination_order
      FROM train_stops
     WHERE stop_id = NEW.destination_stop_id;

    IF v_origin_schedule IS DISTINCT FROM v_destination_sched THEN
        RAISE EXCEPTION '起站與迄站必須屬於同一班次';
    END IF;

    IF v_origin_order >= v_destination_order THEN
        RAISE EXCEPTION '起站順序必須早於迄站';
    END IF;

    SELECT train_id
      INTO v_schedule_train
      FROM train_schedules
     WHERE schedule_id = v_origin_schedule;

    SELECT train_id
      INTO v_seat_train
      FROM seats
     WHERE seat_id = NEW.seat_id;

    IF v_schedule_train IS DISTINCT FROM v_seat_train THEN
        RAISE EXCEPTION '所選座位不屬於此班次的列車';
    END IF;

    SELECT member_id
      INTO v_booking_member
      FROM bookings
     WHERE booking_id = NEW.booking_id;

    SELECT member_id
      INTO v_passenger_member
      FROM passengers
     WHERE passenger_id = NEW.passenger_id;

    IF v_booking_member IS DISTINCT FROM v_passenger_member THEN
        RAISE EXCEPTION '乘客資料不屬於下單會員';
    END IF;

    -- 旅程跨越 n 個停靠序差，就必須存在 n 個相鄰區間。
    SELECT COUNT(*)
      INTO v_segment_count
      FROM schedule_segments AS sg
      JOIN train_stops AS fs ON fs.stop_id = sg.from_stop_id
     WHERE fs.schedule_id = v_origin_schedule
       AND fs.stop_order >= v_origin_order
       AND fs.stop_order < v_destination_order;

    IF v_segment_count <> v_destination_order - v_origin_order THEN
        RAISE EXCEPTION '此班次的相鄰行車區間尚未完整建立';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER bi_booking_items_validate
BEFORE INSERT ON booking_items
FOR EACH ROW
EXECUTE FUNCTION fn_validate_booking_item_insert();

-- 已鎖位後不可直接更換訂單、乘客、座位或行程。
CREATE OR REPLACE FUNCTION fn_prevent_booking_item_trip_update()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
    IF NEW.booking_id IS DISTINCT FROM OLD.booking_id
       OR NEW.passenger_id IS DISTINCT FROM OLD.passenger_id
       OR NEW.seat_id IS DISTINCT FROM OLD.seat_id
       OR NEW.origin_stop_id IS DISTINCT FROM OLD.origin_stop_id
       OR NEW.destination_stop_id IS DISTINCT FROM OLD.destination_stop_id THEN
        RAISE EXCEPTION '不可直接修改已鎖位項目的訂單、乘客、座位或行程';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER bu_booking_items_immutable_trip
BEFORE UPDATE ON booking_items
FOR EACH ROW
EXECUTE FUNCTION fn_prevent_booking_item_trip_update();

-- 新增訂票項目後，自動鎖住旅程涵蓋的每個相鄰區間。
-- 若任一區間已被同一座位占用，複合主鍵會讓整筆交易原子性失敗。
CREATE OR REPLACE FUNCTION fn_reserve_booking_item_segments()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
    INSERT INTO seat_segment_reservations (
        segment_id,
        seat_id,
        booking_item_id
    )
    SELECT
        sg.segment_id,
        NEW.seat_id,
        NEW.booking_item_id
      FROM schedule_segments AS sg
      JOIN train_stops AS fs ON fs.stop_id = sg.from_stop_id
      JOIN train_stops AS os ON os.stop_id = NEW.origin_stop_id
      JOIN train_stops AS ds ON ds.stop_id = NEW.destination_stop_id
     WHERE fs.schedule_id = os.schedule_id
       AND fs.stop_order >= os.stop_order
       AND fs.stop_order < ds.stop_order;

    RETURN NEW;
END;
$$;

CREATE TRIGGER ai_booking_items_reserve_segments
AFTER INSERT ON booking_items
FOR EACH ROW
EXECUTE FUNCTION fn_reserve_booking_item_segments();

-- ----------------------------------------------------------------------------
-- 衍生查詢：訂單總額不重複存入 bookings，而由明細即時計算。
-- ----------------------------------------------------------------------------

CREATE OR REPLACE VIEW v_booking_totals AS
SELECT
    b.booking_id,
    b.booking_number,
    COALESCE(SUM(bi.fare_amount), 0.00::numeric) AS total_amount
FROM bookings AS b
LEFT JOIN booking_items AS bi
       ON bi.booking_id = b.booking_id
GROUP BY b.booking_id, b.booking_number;

COMMENT ON VIEW v_booking_totals IS '依訂票項目即時計算的訂單總額';

COMMIT;
